extends: []
formats: [oas3]
rules:
  openapi-3-1-version:
    description: Ensure the OpenAPI version is 3.1.0
    given: $.openapi
    then:
      function: pattern
      functionOptions:
        match: "^3.1.0$"
    severity: warn
