version: "0.2"
language: en,en-US,de,de-DE
import:
  - "@cspell/dict-de-de/cspell-ext.json"
useGitignore: true
dictionaryDefinitions:
  - name: project-words
    path: "./cspell.words.txt"
    description: "Project-specific terms"
    type: S
dictionaries:
  - en_US
  - node
  - softwareTerms
  - project-words
  - de-de
languageSettings:
  - languageId: "*"
    dictionaries:
      - en_US
      - node
      - softwareTerms
      - de-de
  - languageId: "typescriptreact"
    locale: en,en-US,de,de-DE
    dictionaries:
      - en_US
      - node
      - softwareTerms
      - de-de
  - languageId: "typescript"
    locale: en,en-US,de,de-DE
    dictionaries:
      - en_US
      - node
      - softwareTerms
      - de-de
  - languageId: "javascriptreact"
    locale: en,en-US,de,de-DE
    dictionaries:
      - en_US
      - node
      - softwareTerms
      - de-de
  - languageId: "markdown"
    locale: en,en-US,de,de-DE
    dictionaries:
      - en_US
      - node
      - softwareTerms
      - de-de
  - languageId: "mdx"
    locale: en,en-US,de,de-DE
    dictionaries:
      - en_US
      - node
      - softwareTerms
      - de-de

ignorePaths:
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/.next/**"
  - "**/out/**"
  - "**/dist/**"
  - "**/coverage/**"
  - "**/playwright-report/**"
  - "**/public/**"
  - "**/prisma/migrations/**"
  - "**/package-lock.json"
  - "**/pnpm-lock.yaml"
  - "**/yarn.lock"
  - "**/.turbo/**"
  - "**/.vercel/**"
  - "**/cspell.config.*"
  - "cspell.config.yaml"
