openapi: 3.1.0
info:
  title: Hemera Academy Public API (MVP)
  version: 0.1.0
servers:
  - url: https://hemera.academy
paths:
  /api/courses:
    get:
      summary: List published courses
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          required: false
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
          required: false
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      courses:
                        type: array
                        items:
                          $ref: "#/components/schemas/CourseSummary"
                      pagination:
                        $ref: "#/components/schemas/Pagination"
        "401":
          description: Unauthorized
  /api/courses/{id}:
    get:
      summary: Get course by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/CourseDetail"
        "404":
          description: Not found
components:
  schemas:
    CourseSummary:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
          nullable: true
        slug:
          type: string
        price:
          type: integer
          description: Price in minor units (cent)
        currency:
          type: string
          example: EUR
        capacity:
          type: integer
          nullable: true
        date:
          type: string
          format: date-time
          nullable: true
        isPublished:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        availableSpots:
          type: integer
          nullable: true
        totalBookings:
          type: integer
        userBookingStatus:
          type: string
          nullable: true
    CourseDetail:
      allOf:
        - $ref: "#/components/schemas/CourseSummary"
    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer
        hasNext:
          type: boolean
        hasPrev:
          type: boolean
