openapi: 3.1.0
info:
  title: Hemera Auth & Health API (Spec 001)
  version: 0.1.0
servers:
  - url: https://example.com
paths:
  /api/health:
    get:
      summary: Health check endpoint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]
              examples:
                success:
                  summary: Service is healthy
                  value:
                    status: ok
  /api/auth/providers:
    get:
      summary: List configured auth providers
      responses:
        "200":
          description: Provider list
          content:
            application/json:
              schema:
                type: object
                properties:
                  providers:
                    type: array
                    items:
                      type: string
              examples:
                default:
                  summary: Example provider list
                  value:
                    providers:
                      - email
                      - google
                      - apple
                      - instagram
