name: Check Repo Secrets

on:
  workflow_dispatch:
    inputs:
      fail_on_missing:
        description: 'Fehlende Secrets lassen den Job scheitern'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Report secret presence
        id: report
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          set -euo pipefail

          report() {
            local name="$1"; shift
            local value="$1"; shift || true
            if [ -n "$value" ]; then
              echo "$name=SET"
            else
              echo "$name=MISSING"
            fi
          }

          echo "### Repository Secrets Status" >> "$GITHUB_STEP_SUMMARY"
          echo >> "$GITHUB_STEP_SUMMARY"

          for key in VERCEL_TOKEN VERCEL_PROJECT_ID VERCEL_ORG_ID; do
            val="$(eval echo \"\${$key-}\")"
            if [ -n "$val" ]; then
              echo "- $key: SET" | tee -a "$GITHUB_STEP_SUMMARY"
            else
              echo "- $key: MISSING" | tee -a "$GITHUB_STEP_SUMMARY"
              echo "$key" >> missing.txt
            fi
          done

          if [ -f missing.txt ]; then
            echo "missing=$(paste -sd, missing.txt)" >> "$GITHUB_OUTPUT"
          else
            echo "missing=" >> "$GITHUB_OUTPUT"
          fi

      - name: Fail when requested and missing
        if: ${{ inputs.fail_on_missing == 'true' && steps.report.outputs.missing != '' }}
        run: |
          echo "Fehlende Secrets: ${{ steps.report.outputs.missing }}"
          exit 1
