name: CI (PR target)

on:
  pull_request_target:
    branches: [main]

# Minimal permissions, no secrets needed. We only build/typecheck the PR code.
permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ci-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout PR head (safe)
        uses: actions/checkout@v4
        with:
          # Use the PR head SHA explicitly; do not fetch with write tokens
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc -p tsconfig.json --noEmit

      - name: Lint (CI)
        run: npm run lint:ci

      - name: Build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build
