name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc -p tsconfig.json --noEmit

      - name: Lint
        run: npm run lint:ci

      - name: Unit tests
        run: npm run test:unit -- --ci --reporters=default --reporters=jest-junit
        env:
          CI: 'true'

      - name: Contract tests
        run: npm run test:contracts -- --ci --reporters=default --reporters=jest-junit
        env:
          CI: 'true'

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: '1'

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-build
          path: .next/**
          if-no-files-found: ignore
