name: Docs - cspell

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
  push:
    branches: [main, master]
    paths:
      - '**/*.md'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Run cspell (DE/EN config)
        run: npx cspell lint "**/*.{md,ts,tsx,js}" --no-must-find-files --config ./cspell.config.yaml
