name: Manual Production Deploy

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: 'Git ref to deploy (branch, tag, or SHA)'
        type: string
        required: true
        default: main

concurrency:
  group: manual-production-deploy-${{ github.ref || inputs.target_ref }}
  cancel-in-progress: false

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy-production-manual:
    name: Deploy Production (Manual)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code (target ref)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_ref }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Sanitize Vercel Token
        run: |
          set -euo pipefail
          token=$(printf %s "$VERCEL_TOKEN" | tr -d '"')
          echo "SANITIZED_VERCEL_TOKEN=$token" >> "$GITHUB_ENV"

      - name: Set BUILD_TIME (UTC)
        run: echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_ENV"

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token="$SANITIZED_VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: vercel build --prod --token="$SANITIZED_VERCEL_TOKEN"
        env:
          BUILD_TIME: ${{ env.BUILD_TIME }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          set -euo pipefail
          # Deploy and capture output; avoid clipboard noise for cleaner parsing
          attempts=0
          rc=1
          : > /tmp/vercel_deploy.log
          while [ $attempts -lt 2 ]; do
            attempts=$((attempts+1))
            echo "Attempt $attempts: vercel deploy --prebuilt --prod --yes --token=*** --debug"
            set +e
            vercel deploy --prebuilt --prod --yes --debug --token="$SANITIZED_VERCEL_TOKEN" 2>&1 | tee /tmp/vercel_deploy.log
            rc=$?
            set -e
            [ $rc -eq 0 ] && break
            echo "Vercel deploy attempt $attempts failed with exit $rc. Retrying in 5s..."
            sleep 5
          done
          url=$(grep -Eo 'https://[^[:space:]]+\.vercel\.app' /tmp/vercel_deploy.log | tail -n1 || true)
          if [ -z "${url:-}" ]; then
            echo "::warning::No Vercel URL matched in output. Showing last 120 lines of log:"
            tail -n 120 /tmp/vercel_deploy.log || true
          fi
          if [ "$rc" -ne 0 ] || [ -z "${url:-}" ]; then
            echo "::error::Vercel deploy failed (exit $rc)."
            exit 1
          fi
          echo "Resolved deployment URL: ${url}"
          echo "url=${url}" >> "$GITHUB_OUTPUT"

      - name: Print Deployment URL
        run: echo "Deployment URL=${{ steps.deploy.outputs.url }}"
