name: Manual Production Deploy

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: 'Git ref to deploy (branch, tag, or SHA)'
        type: string
        required: true
        default: main

concurrency:
  group: manual-production-deploy-${{ github.ref || inputs.target_ref }}
  cancel-in-progress: false

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-production-manual:
    name: Deploy Production (Manual)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code (target ref)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Set BUILD_TIME (UTC)
        run: echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_ENV"

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Build Project Artifacts
        run: vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          BUILD_TIME: ${{ env.BUILD_TIME }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "url=$(vercel deploy --prebuilt --prod --token=\"${{ secrets.VERCEL_TOKEN }}\" --yes)" >> "$GITHUB_OUTPUT"

      - name: Print Deployment URL
        run: echo "Deployment URL=${{ steps.deploy.outputs.url }}"
